### ISSUE TITLE
skywalking-live-demo/platform/docker/docker-compose.yaml can not use

### ISSUE THREAD

**Issue by wushifeng** [SkyAPMTest/skywalking-live-demo#21]
In this file skywalking-live-demo/platform/docker/docker-compose.yaml
Thereis not oap server, how to run it?

**Comment by wu-sheng** [comment]
There is no one maintaining this. This is just for some conference showing. 

https://github.com/apache/skywalking-showcase will be(not now) the official repo to make you running demo out of box.
